name: Validate prompts.json

on:
  push:
  pull_request:

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: _schema.json
          INPUT_JSONS: prompts.json
